### ISSUE TITLE
[Feature Request] A Code Question List Page

### ISSUE THREAD

**Issue by DurianZealot** [Education-Victory/Education-Victory#32]
## Code Question List (问题列表)

- This should be a page used for **showing the list of all coding questions available** in the website, similar to how **leetcode** shows the list of questions. However, it contains less information. 

- The following is a list of features that should be included on this page (Ranked from high priority to low priority)

  - [ ] A table to show all coding questions available 

  - [ ] Search questions by questions' title and categories

  - [ ] A page linked to each question for users to update some status on their progress in solving it.

  - [ ] If a question has follow-up questions, the follow-up question should be listed as well.

  - [ ] Filters for questions based on some criteria

**Comment by Windsooon** [comment]
> This should be a page used for showing the list of all coding questions available in the website, similar to how leetcode shows the list of questions.

Yes. you can checkout https://brilliant.org/ to see how it works.
