### ISSUE TITLE
[Feature Request]Need a Quiz for evaluation of users' ability in solving coding questions

### ISSUE THREAD

**Issue by DurianZealot** [Education-Victory/Education-Victory#35]
## Quiz for evaluation of users' ability in solving coding questions 

- When users first sign in to the website, if users cannot make a good estimation of their skills in solving coding questions and do not know what code questions to start with, it would be great for them to do a  set of questions to evaluate their skills and find a good match for questions to initial their progress in learning algorithms. 

The following lists of features to be implemented in the section (ranked from high priority to low priority):

- [ ] A page for the evaluation quiz 
- [ ] Calculate the score of the quiz submission 
- [ ] Collect 20 - 30 questions for the quiz (data structure and algorithm related)
- [ ] A page listing all quizzes

**Comment by Windsooon** [comment]
LGTM
