### ISSUE TITLE
[Feature Request] Personal Setting Page

### ISSUE THREAD

**Issue by DurianZealot** [Education-Victory/Education-Victory#38]
## Personal Setting Page

- There should be a page for users to personalize their accounts and view their progress and recent activities.

The following lists all features that should be included (ranked from high priority to low priority):

- [ ] Personal Information Settings (nickname, password, profile pictures, etc.)
- [ ] Foci in coding topics (hexagon)
- [ ] Rank among all users 
- [ ] Accumulated score 
- [ ] Records of submission
- [ ] Recent discussion

**Comment by Windsooon** [comment]
LGTM
