### ISSUE TITLE
Create models for Coding Ability Evaluation

### ISSUE THREAD

**Issue by DurianZealot** [Education-Victory/Education-Victory#43]
In order to make a quiz for the coding ability evaluation, I suggest having models for
- [ ] quiz 
- [ ] each quiz question
- [ ] each option for a question
- [ ] record for quiz submission (answer for each question should be recorded for further analysis)

-------

Related to #35

**Comment by Windsooon** [comment]
>  No need to record a user's choice for each question in the quiz.

I think we still need to record every quiz the user had solved, how many time they use to solve it, and what is the choice, correct or not. We can use this info for data analyise.
