### ISSUE TITLE
[documentation] Front Page 1.2 AlgoBuilder - content list

### ISSUE THREAD

**Issue by wenboji** [Education-Victory/Education-Victory#60]
### Success examples of deliberate practice and collaborative learning
> story behind RSA algo
### Steps of the methodologies
- A
- B
- C
- X features of education-X for the step X showcase
### Client reviews and success examples after using Education-X

**Comment by Windsooon** [comment]
I know some stories like RSA, However, I prefer to tell the story about the algorithms which may show up during the tech interview, like Floyd's Cycle Detection Algorithm, Boyer–Moore, Dijkstra, Bellman-Ford, Floyd-Warshall, KMP. I guess users may like these stories.If you have time, maybe you can try to draw a simple picture for your idea, Bulma provides some examples templates and you can have a look at them.
