### ISSUE TITLE
[Documentation] Selected Coding Questions

### ISSUE THREAD

**Issue by DurianZealot** [Education-Victory/Education-Victory#94]
## Longest Palindrome Substring 

- https://leetcode.cn/problems/longest-palindromic-substring/

- Methods: 

  - DP
  - Expansion from center
  - Manacher

- Follow Up:

  - #### [[Longest Palindromic Subsequence](https://leetcode.cn/problems/longest-palindromic-subsequence/)](https://leetcode.cn/problems/longest-palindromic-subsequence/) 

    

## Regular Expression Matching

- https://leetcode.cn/problems/regular-expression-matching/

- Methods:

  - DP
  - Recursion

- Follow Up:

  - #### [[Wildcard Matching](https://leetcode.cn/problems/wildcard-matching/)](https://leetcode.cn/problems/wildcard-matching/)

  

## Generate Parentheses

- https://leetcode.cn/problems/generate-parentheses/

- Methods:

  - Backtracking by BFS, DFS
  - DP 

- Follow Up:

  - #### [[Letter Combinations of a Phone Number](https://leetcode.cn/problems/letter-combinations-of-a-phone-number/)](https://leetcode.cn/problems/letter-combinations-of-a-phone-number/)

  

## House Robber

- https://leetcode.cn/problems/house-robber/

- Methods: 

  - DP 

- Follow Up:  

  - LeetCode 213, 337

## Best Time to Buy and Sell Stock 

- https://leetcode.cn/problems/best-time-to-buy-and-sell-stock/

- Methods:

  - DP
  - Greedy

- Follow Up:

  - LeetCode 122 / 123 / 188 / 309 / 714

  

## Coin Change 

- https://leetcode.cn/problems/coin-change/

- Methods:

  - DP
  - BFS

- Follow Up:

  - LeetCode 518

  

## Number of Islands

- https://leetcode.cn/problems/number-of-islands/

- Methods:

  - DFS
  - BFS
  - Union Find

- Follow Up:

  - LeetCode 200 / 463 / 695 / 827 

  

## Maximum Depth of Binary Tree

- https://leetcode.cn/problems/maximum-depth-of-binary-tree/

- Methods:

  - BFS
  - DFS

- Follow Up: 

  - https://leetcode.cn/problems/balanced-binary-tree/
  - https://leetcode.cn/problems/minimum-depth-of-binary-tree/

  ## Path Sum

- https://leetcode.cn/problems/path-sum/
- Methods:
  - DFS
  - BFS
  - Backtracking
  - Stack
- Follow Up:
  - LeetCode 113 / 437 / 666 / 124 / 64

## Course Schedule 

- https://leetcode.cn/problems/course-schedule/
- Methods:
  - DFS
  - BFS
  - Topological Sort
- Follow Up:
  - LeetCode 210 / 630 / 1462 

## Network Delay Time

- https://leetcode.cn/problems/network-delay-time/
- Methods:
  - Dijstrka

- Follow Up:

## Cheapest Flights Within K Stops

- https://leetcode.cn/problems/cheapest-flights-within-k-stops/ 
- Methods:
  - Bellman Ford
  - DP

- Follow Up:

## Two Sum 

- https://leetcode.cn/problems/two-sum/
- Methods:
  - Two Pointers 
- Follow Up:
  - LeetCode 3Sum Closest / 4Sum / 3Sum Smaller

## Meeting Rooms

- https://leetcode.cn/problems/meeting-rooms/
- Methods:
  - Sorting
  - Greedy
- Follow Up:
  - LeetCode 253 / 2402 / 56 / 57 

## Find Median from Data Stream 

- https://leetcode.cn/problems/find-median-from-data-stream/
- Methods:
  - Priority Queue / Heap
- Follow Up:

## Trapping Rain Water 

- https://leetcode.cn/problems/trapping-rain-water/
- Methods:
  - DP 
  - Monotonic Stack
  - Two Pointers

- Follow Up:
  - LeetCode 407

## Decode String 

- https://leetcode.cn/problems/decode-string/
- Methods:
  - Stack 
  - Recursion
- Follow Up:
  - LeetCode 726 

## Valid Parenthese

- https://leetcode.cn/problems/valid-parentheses/
- Methods:
  - Stack
- Follow Up:
  - LeetCode 32

## Implement Stack using Queues

- https://leetcode.cn/problems/implement-stack-using-queues/
- Methods:
  - Queue + Design 

- Follow Up:

## Jump Game VI 

- https://leetcode.cn/problems/jump-game-vi/

- Methods:
  - DP + Priority Queue
  - DP + Monotonic Queue
- Follow Up:
  - LeetCode 55 / 45 / 1306 / 1340 / 1345 / 1871 / 2297

## LRU Cache

- https://leetcode.cn/problems/lru-cache/
- Methods:
  - Design
  - Hash Table
  - Linked List
- Follow Up:

## Min Stack 

- https://leetcode.cn/problems/min-stack/
- Methods:
  - Design
  - Stack
- Follow Up:

## Min Stack 

- https://leetcode.cn/problems/min-stack/
- Methods:
  - Design
  - Stack
- Follow Up:

#### Kth Largest Element in a Stream

- https://leetcode.cn/problems/kth-largest-element-in-a-stream/
- Methods:
  - Design
  - Heap
- Follow Up:

**Comment by Windsooon** [comment]
Wenbo and I have some new ideas how to define and choose questions, You may need to discuss with him before create your PR.
